# Generated by Django 5.0 on 2023-12-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avocat_is_activate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avocat',
            name='is_activate',
        ),
    ]
