# Generated by Django 5.0 on 2024-01-24 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rendez_vous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendez_vous',
            name='date',
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='time',
            field=models.CharField(choices=[('8 AM', '8 AM'), ('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM')], default='8 PM', max_length=10),
        ),
    ]
