# Generated by Django 5.0 on 2024-01-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_rendez_vous_date_rendez_vous_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendez_vous',
            name='day',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.avocat')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
    ]
